version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: {데이터 베이스 비밀번호}
      MYSQL_DATABASE: starbucks
      MYSQL_USER: root
      MYSQL_PASSWORD: {데이터 베이스 비밀번호}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  mysql-data:
  redis-data: