spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  data:
    redis:
      port: 6379
      host: 127.0.0.1

secret:
  key: ${JWT_SECRET_KEY}

coolsms:
  api:
    key: ${COOLSMS_KEY}
    secret: ${COOLSMS_SECRET_KEY}

sendNumber: ${SEND_NUMBER}
